# Generated by Django 6.0.1 on 2026-01-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_brand_clothesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothesmodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='clothes/'),
        ),
    ]
