# Generated by Django 6.0.1 on 2026-01-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_clothesmodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание о себе'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='english_level',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Уровень английского'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='experience',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Опыт работы (лет)'),
        ),
    ]
