# Generated by Django 6.0.1 on 2026-01-20 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_alter_clothesmodel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothesmodel',
            old_name='image',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='clothesmodel',
            name='brands',
        ),
        migrations.RemoveField(
            model_name='clothesmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='clothesmodel',
            name='title',
        ),
        migrations.AddField(
            model_name='clothesmodel',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clothes.brand'),
        ),
        migrations.AddField(
            model_name='clothesmodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clothesmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Бренд'),
        ),
    ]
