# Generated by Django 6.0 on 2026-01-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='review',
            name='author_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя автора'),
        ),
    ]
