# Generated by Django 6.0.1 on 2026-01-20 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
        ('clothes', '0003_rename_image_clothesmodel_photo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='address',
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='email',
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='product',
        ),
        migrations.AddField(
            model_name='basketitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clothes.clothesmodel'),
        ),
        migrations.AddField(
            model_name='basketitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
